# Generated by Django 5.2.4 on 2025-07-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cadastrale', models.CharField(max_length=50, unique=True)),
                ('cni', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('prenom', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type_proprietaire', models.CharField(choices=[('public', 'Public'), ('prive', 'Prive')], default='prive', max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('proprietaire', 'Proprietaire')], default='proprietaire', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_activation', models.DateTimeField(auto_now_add=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
        ),
    ]
