# Generated by Django 5.2.4 on 2025-08-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotissement', '0004_alter_lotissement_addresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotissement.parcelle')),
            ],
        ),
    ]
