# Generated by Django 5.2.4 on 2025-07-30 14:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longeur', models.FloatField()),
                ('superficie_m2', models.FloatField(default=0, verbose_name='Superficie (m²)')),
                ('perimetre_m', models.FloatField(default=0, verbose_name='Périmètre (m)')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, verbose_name='Polygone de la parcelle')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('addresse', models.CharField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lotissement',
                'verbose_name_plural': 'Lotissements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longeur', models.FloatField()),
                ('superficie_m2', models.FloatField(default=0, verbose_name='Superficie (m²)')),
                ('perimetre_m', models.FloatField(default=0, verbose_name='Périmètre (m)')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, verbose_name='Polygone de la parcelle')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('longeur', models.FloatField()),
                ('superficie_m2', models.FloatField(default=0, verbose_name='Superficie (m²)')),
                ('perimetre_m', models.FloatField(default=0, verbose_name='Périmètre (m)')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, verbose_name='Polygone de la parcelle')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloc_lotissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotissement.lotissement')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longeur', models.FloatField()),
                ('superficie_m2', models.FloatField(default=0, verbose_name='Superficie (m²)')),
                ('perimetre_m', models.FloatField(default=0, verbose_name='Périmètre (m)')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, verbose_name='Polygone de la parcelle')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcelle_bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='lotissement.bloc')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='bloc',
            constraint=models.UniqueConstraint(fields=('name', 'bloc_lotissement'), name='unique_bloc_per_lotissement'),
        ),
    ]
