# Generated by Django 4.2 on 2025-07-23 04:17

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longeur', models.FloatField()),
                ('superficie_m2', models.FloatField(default=0, verbose_name='Superficie (m²)')),
                ('perimetre_m', models.FloatField(default=0, verbose_name='Périmètre (m)')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, verbose_name='Polygone de la parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('geometry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lotissement.geometry')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('lotissement.geometry',),
        ),
        migrations.CreateModel(
            name='Lotissement',
            fields=[
                ('geometry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lotissement.geometry')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('addresse', models.CharField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lotissement',
                'verbose_name_plural': 'Lotissements',
                'ordering': ['name'],
            },
            bases=('lotissement.geometry',),
        ),
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('geometry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lotissement.geometry')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('lotissement.geometry',),
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('geometry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lotissement.geometry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcelle_bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='lotissement.bloc')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('lotissement.geometry',),
        ),
        migrations.AddField(
            model_name='bloc',
            name='bloc_lotissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotissement.lotissement'),
        ),
    ]
