# Generated by Django 5.2.4 on 2025-07-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotissement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloc',
            name='longeur',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lotissement',
            name='longeur',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lotissement',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='longeur',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rue',
            name='longeur',
            field=models.FloatField(default=0, null=True),
        ),
    ]
