# Generated by Django 5.2.4 on 2025-08-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotissement', '0002_alter_bloc_longeur_alter_lotissement_longeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotissement',
            name='addresse',
            field=models.CharField(),
        ),
    ]
