# Generated by Django 5.2.4 on 2025-08-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotissement', '0003_alter_lotissement_addresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotissement',
            name='addresse',
            field=models.CharField(null=True),
        ),
    ]
